# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Test Base results

on:
  push:
  schedule:
     - cron:  '0 0 * * *'
     
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dotenv
      run: |
        pip install python-dotenv
    - name: Install azure-identity
      run: |
        pip install azure-identity
    - name: Install azure-testbase
      run: |
       pip install azure-mgmt-testbase
    - name: AzureLoginSample      
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: Run test base script      
      id: testbase
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}        
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        TESTBASE_ACCOUNT_NAME: ${{ secrets.TESTBASE_ACCOUNT_NAME }}
      run: |
        echo Running script
        python ./HeightGained/scripts/testbase.py
     
       
   
