name: Build and deploy to Test Base

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'Best-Practices/HeightGained-GitHub-Pipeline-Integration/HeightGained/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'Best-Practices/HeightGained-GitHub-Pipeline-Integration/HeightGained/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Best-Practices/HeightGained-GitHub-Pipeline-Integration/HeightGained
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Best-Practices/HeightGained-GitHub-Pipeline-Integration/HeightGained
    - name: Compress to Package
      run: ./compress.ps1
      working-directory: ./Best-Practices/HeightGained-GitHub-Pipeline-Integration/HeightGained/utilities
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install azure-identity
      run: |
        pip install azure-identity
    - name: Install azure-storage-blob
      run: |
        pip install azure-storage-blob
    - name: Install azure-testbase
      run: |
       pip install azure-mgmt-testbase==1.0.0b1
    - name: Run test base script      
      id: testbase
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}        
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        TESTBASE_ACCOUNT_NAME: ${{ secrets.TESTBASE_ACCOUNT_NAME }}
        APPLICATION_NAME: HeightGained
        APPLICATION_VERSION: 1.0.0
        OSS_TO_TEST: Windows 10 21H2, Windows 11 21H2
        PACKAGE_FILE_PATH: ./HeightGained.zip
        SCRIPT_PATH_INSTALL: scripts/install.ps1
        SCRIPT_PATH_LAUNCH: scripts/launch.ps1
        SCRIPT_PATH_CLOSE: scripts/close.ps1
        SCRIPT_PATH_UNINSTALL: scripts/uninstall.ps1
      run: |
        echo Running upload_package.py
        python ./upload_package.py
      working-directory: ./Best-Practices/HeightGained-GitHub-Pipeline-Integration/HeightGained/utilities
